# Site settings
title:       Turquoise
description: A pretty programmer
email:
baseurl:     ""
url:         "http://salwa.bitballoon.com" # the base hostname & protocol for your site

keywords:    >
  html, css, javascript, ruby, rails, angularjs, reactjs, web development
version:     1.0.0
github:
  repo:      https://github.com/mnishiguchi/turquoise

# About/contact
author:
  name:                Masatoshi Nishiguchi
  # url:               http://mnishiguchi.com
  # email:             nishiguchi.masa@gmail.com
  # github_url:        https://github.com/mnishiguchi
  # linkedin_url:      https://linkedin.com/in/mnishiguchi
  # twitter_url:       https://twitter.com/mnishiguchiDC
  # stackoverflow_url: http://stackoverflow.com/users/3837223/mnishiguchi

# Url and Permalinks
permalink:  pretty
url:        https://mnishiguchi.github.io/turquoise  # Hostname & protocol for your site
baseurl:    ""

# Navigation links in the header of the website
pages_list:
  Home:        '/'
  About:       '/about'
  Education:   '/education'
  Future:      '/future'
  Cooking:     '/cooking'
  Programming: '/programming'
  Hobbies:     '/hobbies'
  Pyramid:     '/pyramid'

# Assets
sass:
  sass_dir: _sass  # Specify the directory that contains sass partials.
  style:    :compressed

# Include custom directories
include: ['_pages']

# Feed
feed: false

# Gems
gems:
  # - jekyll-paginate
  # - jekyll-gist
  # - jekyll-redirect-from
# The jekyll-redirect-from gem allows URL Redirects: https://help.github.com/articles/redirects-on-github-pages
